operator_separator = '#'
red_rgb_tuple = (255, 0, 0)
green_rgb_tuple = (0, 255, 0)
blue_rgb_tuple = (0, 0, 255)
FRUITS_LINK = 'fruits@https://artmapstore.blob.core.windows.net/firstnodes/fruits.tsv'
ROOT_LINK = FRUITS_LINK
z_limit_caching = 20
cache_limit = 10 ** 6
cache_populate_limit = 10 ** 5
default_tile_resolution = 256
LINE_LINK = 'line@https://artmapstore.blob.core.windows.net/firstnodes/line.tsv.gz'
RED_GALLERY_LINK = 'red_gallery@https://artmapstore.blob.core.windows.net/firstnodes/red_gallery.tsv.gz'
color_channels_used = 3
gallery_file_url = 'https://artmapstore.blob.core.windows.net/firstnodes/gallery_file.tsv'
version_string = 'ver_'
welcome_link = 'welcome@https://artmapstore.blob.core.windows.net/firstnodes/welcome_kaii.ver_0.tsv'
WELCOME_IMAGE = 'https://artmapstore.blob.core.windows.net/firstnodes/photos/welcome_to_kaii.JPG'
azure_base_filename = 'https://artmapstore.blob.core.windows.net/firstnodes'
amazon_s3_base_filename = 'https://s3-us-west-2.amazonaws.com/graphnodes/first'
separator_character = '@'
children_per_node = 4
anonymous_username = 'anonymous'
seattle_skyline_url = 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Seattle_Skyline_tiny.jpg'
