# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagetree.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imagetree.proto',
  package='imagetree_core',
  syntax='proto3',
  serialized_pb=_b('\n\x0fimagetree.proto\x12\x0eimagetree_core\"3\n\x05Pixel\x12\t\n\x01r\x18\x01 \x01(\x05\x12\t\n\x01g\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\x12\t\n\x01\x61\x18\x04 \x01(\x05\"\x18\n\x08\x43hildren\x12\x0c\n\x04name\x18\x01 \x03(\t\"{\n\tImageTree\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x05pixel\x18\x02 \x01(\x0b\x32\x15.imagetree_core.Pixel\x12*\n\x08\x63hildren\x18\x03 \x01(\x0b\x32\x18.imagetree_core.Children\x12\x0e\n\x06imgurl\x18\x04 \x01(\t\"8\n\x0bImageForest\x12)\n\x06\x66orest\x18\x01 \x03(\x0b\x32\x19.imagetree_core.ImageTreeb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PIXEL = _descriptor.Descriptor(
  name='Pixel',
  full_name='imagetree_core.Pixel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='imagetree_core.Pixel.r', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g', full_name='imagetree_core.Pixel.g', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='imagetree_core.Pixel.b', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='a', full_name='imagetree_core.Pixel.a', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=86,
)


_CHILDREN = _descriptor.Descriptor(
  name='Children',
  full_name='imagetree_core.Children',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='imagetree_core.Children.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=112,
)


_IMAGETREE = _descriptor.Descriptor(
  name='ImageTree',
  full_name='imagetree_core.ImageTree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='imagetree_core.ImageTree.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pixel', full_name='imagetree_core.ImageTree.pixel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children', full_name='imagetree_core.ImageTree.children', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgurl', full_name='imagetree_core.ImageTree.imgurl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=237,
)


_IMAGEFOREST = _descriptor.Descriptor(
  name='ImageForest',
  full_name='imagetree_core.ImageForest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forest', full_name='imagetree_core.ImageForest.forest', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=295,
)

_IMAGETREE.fields_by_name['pixel'].message_type = _PIXEL
_IMAGETREE.fields_by_name['children'].message_type = _CHILDREN
_IMAGEFOREST.fields_by_name['forest'].message_type = _IMAGETREE
DESCRIPTOR.message_types_by_name['Pixel'] = _PIXEL
DESCRIPTOR.message_types_by_name['Children'] = _CHILDREN
DESCRIPTOR.message_types_by_name['ImageTree'] = _IMAGETREE
DESCRIPTOR.message_types_by_name['ImageForest'] = _IMAGEFOREST

Pixel = _reflection.GeneratedProtocolMessageType('Pixel', (_message.Message,), dict(
  DESCRIPTOR = _PIXEL,
  __module__ = 'imagetree_pb2'
  # @@protoc_insertion_point(class_scope:imagetree_core.Pixel)
  ))
_sym_db.RegisterMessage(Pixel)

Children = _reflection.GeneratedProtocolMessageType('Children', (_message.Message,), dict(
  DESCRIPTOR = _CHILDREN,
  __module__ = 'imagetree_pb2'
  # @@protoc_insertion_point(class_scope:imagetree_core.Children)
  ))
_sym_db.RegisterMessage(Children)

ImageTree = _reflection.GeneratedProtocolMessageType('ImageTree', (_message.Message,), dict(
  DESCRIPTOR = _IMAGETREE,
  __module__ = 'imagetree_pb2'
  # @@protoc_insertion_point(class_scope:imagetree_core.ImageTree)
  ))
_sym_db.RegisterMessage(ImageTree)

ImageForest = _reflection.GeneratedProtocolMessageType('ImageForest', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEFOREST,
  __module__ = 'imagetree_pb2'
  # @@protoc_insertion_point(class_scope:imagetree_core.ImageForest)
  ))
_sym_db.RegisterMessage(ImageForest)


# @@protoc_insertion_point(module_scope)
